VENDOR=ciena
NAME=waverouter
IMAGE_GLOB=*.qcow2
IMAGE=WR1-CTM.qcow2

ifndef VERSION
$(error VERSION is not set. Usage: make VERSION=wr-xx-xx-xx-xxxx)
endif

-include ../makefile-sanity.include
-include ../makefile.include
