VENDOR=ciena
NAME=waverouter
IMAGE_GLOB=*.qcow2
IMAGE=WR1-CTM.qcow2

# match versions like:
# 10-10-01-0182
# VERSION=$(shell echo $(IMAGE) | sed -e 's/meta_//' | sed -e 's/-core-x86-64-disk.qcow2//')
#fix this later
VERSION=wr-10-09-02-0572

-include ../makefile-sanity.include
-include ../makefile.include
