VENDOR=Ciena
NAME=SAOS 10.x
IMAGE_FORMAT=qcow
IMAGE_GLOB=*.qcow2
IMAGE=meta_10-10-01-0182-core-x86-64-disk.qcow2

# match versions like:
# 202305
# VERSION=$(shell echo $(IMAGE) | sed -e 's/sonic-vs-//' | sed -e 's/.qcow2//')
VERSION="01-10-01-0182"

-include ../makefile-sanity.include
-include ../makefile.include
